package edu.ub.prog2.GonzalezDiezMarc.vista;


import edu.ub.prog2.GonzalezDiezMarc.controlador.CtrlReproductor;
import edu.ub.prog2.GonzalezDiezMarc.model.ExcepcioFitxerNoExisteix;
import edu.ub.prog2.GonzalezDiezMarc.model.ExcepcioFitxerRepetit;
import edu.ub.prog2.GonzalezDiezMarc.model.FitxerAudio;
import edu.ub.prog2.GonzalezDiezMarc.model.LlistaFitxers;
import edu.ub.prog2.GonzalezDiezMarc.model.LlistaReproduccio;
import edu.ub.prog2.utils.FitxerAudioErrorException;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mat.aules
 */
public class ReproductorUB4 extends javax.swing.JFrame {

    /**
     * Creates new form FrmTest
     */
    private CtrlReproductor control;
    private DefaultListModel modelBiblioteca;
    private DefaultListModel modelLlistes;
    
    public ReproductorUB4() {
        control = new CtrlReproductor();
        modelBiblioteca = new DefaultListModel();
        modelLlistes = new DefaultListModel();
        initComponents();
        llistaBiblioteca.setModel(modelBiblioteca);
        llistaLlistes.setModel(modelLlistes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JToggleButton();
        btnSeguent = new javax.swing.JButton();
        btnCiclica = new javax.swing.JToggleButton();
        btnAleatoria = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        llistaBiblioteca = new javax.swing.JList();
        btnReproduirBiblioteca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaLlistes = new javax.swing.JList();
        btnCarregarLlista = new javax.swing.JButton();
        btnAfegirALlista = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboxllistaLlistes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnEliminarArxiuLlista = new javax.swing.JButton();
        btnAfegirCanco = new javax.swing.JButton();
        btnEliminarCancoBiblio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarLlista = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnSortir = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPlayPause.setText(">|");
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        btnSeguent.setText(">>");
        btnSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguentActionPerformed(evt);
            }
        });

        btnCiclica.setText("↪ ");
        btnCiclica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiclicaActionPerformed(evt);
            }
        });

        btnAleatoria.setText("⇄");
        btnAleatoria.setPreferredSize(new java.awt.Dimension(47, 23));
        btnAleatoria.setRequestFocusEnabled(false);
        btnAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriaActionPerformed(evt);
            }
        });

        llistaBiblioteca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        llistaBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llistaBibliotecaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(llistaBiblioteca);

        btnReproduirBiblioteca.setText("Carregar Biblioteca");
        btnReproduirBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduirBibliotecaActionPerformed(evt);
            }
        });

        llistaLlistes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(llistaLlistes);

        btnCarregarLlista.setText("Carregar Llista");
        btnCarregarLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarLlistaActionPerformed(evt);
            }
        });

        btnAfegirALlista.setText("Afegir a la llista el seleccionat");
        btnAfegirALlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirALlistaActionPerformed(evt);
            }
        });

        jLabel4.setText("Biblioteca");

        cboxllistaLlistes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxllistaLlistesActionPerformed(evt);
            }
        });

        jButton1.setText("▄");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminarArxiuLlista.setText("Eliminar de la llista el seleccionat");
        btnEliminarArxiuLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArxiuLlistaActionPerformed(evt);
            }
        });

        btnAfegirCanco.setText("Afegir arxiu");
        btnAfegirCanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirCancoActionPerformed(evt);
            }
        });

        btnEliminarCancoBiblio.setText("Eliminar arxiu seleccionat");
        btnEliminarCancoBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCancoBiblioActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/GonzalezDiezMarc/vista/logo_UB.gif"))); // NOI18N

        btnEliminarLlista.setText("Eliminar llista sencera");
        btnEliminarLlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLlistaActionPerformed(evt);
            }
        });

        jMenu5.setText("Arxiu");

        jMenu7.setText("Biblioteca");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Afegir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenu5.add(jMenu7);

        jMenu8.setText("Llista de reproducció");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Crear Llista");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenu5.add(jMenu8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Guardar dades");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Recuperar dades");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        mnSortir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnSortir.setText("Sortir");
        mnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSortirActionPerformed(evt);
            }
        });
        jMenu5.add(mnSortir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnCarregarLlista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnEliminarArxiuLlista, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminarLlista, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnAfegirALlista, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboxllistaLlistes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnSeguent, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                            .addComponent(btnCiclica)
                            .addGap(8, 8, 8)
                            .addComponent(btnAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAfegirCanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminarCancoBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnReproduirBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxllistaLlistes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnAfegirALlista))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEliminarArxiuLlista)
                                .addComponent(btnEliminarLlista))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAfegirCanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarCancoBiblio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReproduirBiblioteca)
                            .addComponent(btnCarregarLlista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAleatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCiclica)
                            .addComponent(btnSeguent)
                            .addComponent(jButton1)
                            .addComponent(btnPlayPause)
                            .addComponent(btnAnterior))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSortirActionPerformed
        this.setVisible(false);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mnSortirActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        DlgCrearLlista dialog = new DlgCrearLlista(this,true,control);
        dialog.setTitle("Afegir llista");
        dialog.pack();
        dialog.setVisible(true);
        omplirLlista();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed

            try {
                control.setPlayPause();
            } catch (FitxerAudioErrorException ex) {
                Logger.getLogger(ReproductorUB4.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnPlayPauseActionPerformed
    private void omplirLlista(){
        modelBiblioteca.clear();
        cboxllistaLlistes.removeAllItems();
        modelLlistes.clear();
        
        for(int i = 0; i < control.getBiblioteca().tamany(); i++){
            modelBiblioteca.addElement(control.getBiblioteca().getAt(i));
        }
        
        ArrayList<LlistaReproduccio> lista = control.getLlistes();
        for (int i = 0; i < control.tamanyLlistes(); i++){
            cboxllistaLlistes.addItem(lista.get(i).getTitol());
        }
        
    }
    private void btnReproduirBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduirBibliotecaActionPerformed
        control.playBiblioteca();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReproduirBibliotecaActionPerformed

    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed

            try {
                control.setSeguent();
            } catch (FitxerAudioErrorException ex) {
                Logger.getLogger(ReproductorUB4.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnSeguentActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        File fitxer = new File("dades.dat");
        try{
            control.guardarDades(fitxer);
            DadesOk dialog = new DadesOk(this,true);
            dialog.setTitle("Guardat correctament.");
            dialog.pack();
            dialog.setVisible(true);
        }catch(Exception e){
            DadesFalse dialog = new DadesFalse(this,true);
            dialog.setTitle("Error");
            dialog.pack();
            dialog.setVisible(true);
        }
  
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        cboxllistaLlistes.removeAllItems();
        modelBiblioteca.clear();
        modelLlistes.clear();
        File fitxer = new File("dades.dat");

        control.setStop();
        try{
            control.recuperarDades(fitxer);
            DadesOk dialog = new DadesOk(this,true);
            dialog.setTitle("Recuperat correctament.");
            dialog.pack();
            dialog.setVisible(true);
        }catch(Exception e){
            DadesFalse dialog = new DadesFalse(this,true);
            dialog.setTitle("Error");
            dialog.pack();
            dialog.setVisible(true);
        }

        control.setStop();
        omplirLlista();
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
            try {
                control.setAnterior();
            } catch (FitxerAudioErrorException ex) {
                Logger.getLogger(ReproductorUB4.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAfegirALlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirALlistaActionPerformed
        int index = llistaBiblioteca.getSelectedIndex();
        int indexx = cboxllistaLlistes.getSelectedIndex();
        control.afegirFitxerLlista(index,indexx);
        omplirLlista();
    }//GEN-LAST:event_btnAfegirALlistaActionPerformed

    private void btnCarregarLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarLlistaActionPerformed
        int index = cboxllistaLlistes.getSelectedIndex();
        control.playLlista(index);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCarregarLlistaActionPerformed

    private void cboxllistaLlistesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxllistaLlistesActionPerformed
        int indexLista = cboxllistaLlistes.getSelectedIndex();
        modelLlistes.clear();
        try{
            LlistaReproduccio llista = control.getLlista(indexLista);
            for (int i = 0; i < llista.tamany(); i++){
            modelLlistes.addElement(llista.getAt(i));
        }
        }catch(ArrayIndexOutOfBoundsException e){}

// TODO add your handling code here:
    }//GEN-LAST:event_cboxllistaLlistesActionPerformed

    private void llistaBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaBibliotecaMouseClicked
        if (evt.getClickCount() == 2) {
            control.playSong(llistaBiblioteca.getSelectedIndex());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_llistaBibliotecaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.setStop();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        VisorDialog dialog = new VisorDialog(this,true,control);
        dialog.setTitle("Afegir arxiu");
        dialog.pack();
        dialog.setVisible(true);
        omplirLlista();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnCiclicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiclicaActionPerformed
        control.setCiclica();
    }//GEN-LAST:event_btnCiclicaActionPerformed

    private void btnAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriaActionPerformed
        control.setAleatoria();
    }//GEN-LAST:event_btnAleatoriaActionPerformed

    private void btnAfegirCancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirCancoActionPerformed
        VisorDialog dialog = new VisorDialog(this,true,control);
        dialog.setTitle("Afegir arxiu");
        dialog.pack();
        dialog.setVisible(true);
        omplirLlista();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAfegirCancoActionPerformed

    private void btnEliminarArxiuLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArxiuLlistaActionPerformed

        control.eliminarFitxerLlista(llistaLlistes.getSelectedIndex(),cboxllistaLlistes.getSelectedIndex());
        omplirLlista();
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarArxiuLlistaActionPerformed

    private void btnEliminarLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLlistaActionPerformed
        control.eliminarLlistaReproduccio(cboxllistaLlistes.getSelectedIndex()); 
        omplirLlista();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarLlistaActionPerformed

    private void btnEliminarCancoBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCancoBiblioActionPerformed
        control.eliminarFitxer(control.getBiblioteca().getAt(llistaBiblioteca.getSelectedIndex()));
        omplirLlista();// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCancoBiblioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReproductorUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReproductorUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirALlista;
    private javax.swing.JButton btnAfegirCanco;
    private javax.swing.JToggleButton btnAleatoria;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCarregarLlista;
    private javax.swing.JToggleButton btnCiclica;
    private javax.swing.JButton btnEliminarArxiuLlista;
    private javax.swing.JButton btnEliminarCancoBiblio;
    private javax.swing.JButton btnEliminarLlista;
    private javax.swing.JToggleButton btnPlayPause;
    private javax.swing.JButton btnReproduirBiblioteca;
    private javax.swing.JButton btnSeguent;
    private javax.swing.JComboBox cboxllistaLlistes;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList llistaBiblioteca;
    private javax.swing.JList llistaLlistes;
    private javax.swing.JMenuItem mnSortir;
    // End of variables declaration//GEN-END:variables
}
